// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.protobuff;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_employee_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_employee_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_employee_Employee_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_employee_Employee_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_employee_EmployeeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_employee_EmployeeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\022\036ashok.protobufexample." +
      "employee\"\315\002\n\010Employee\022\016\n\006emp_id\030\001 \001(\005\022\016\n" +
      "\006salary\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\017\n\007address\030\004" +
      " \001(\t\022\022\n\ndepartment\030\005 \001(\t\022\r\n\005email\030\006 \001(\t\022" +
      "\013\n\003age\030\007 \001(\005\022D\n\006phones\030\010 \003(\01324.ashok.pro" +
      "tobufexample.employee.Employee.PhoneNumb" +
      "er\032_\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022@\n\004typ" +
      "e\030\002 \001(\01622.ashok.protobufexample.employee" +
      ".Employee.PhoneType\"+\n\tPhoneType\022\n\n\006MOBI" +
      "LE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"J\n\014EmployeeList" +
      "\022:\n\010employee\030\001 \003(\0132(.ashok.protobufexamp" +
      "le.employee.EmployeeB(\n\025com.example.prot" +
      "obuffB\rCustomerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ashok_protobufexample_employee_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ashok_protobufexample_employee_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_employee_Employee_descriptor,
        new java.lang.String[] { "EmpId", "Salary", "Name", "Address", "Department", "Email", "Age", "Phones", });
    internal_static_ashok_protobufexample_employee_Employee_PhoneNumber_descriptor =
      internal_static_ashok_protobufexample_employee_Employee_descriptor.getNestedTypes().get(0);
    internal_static_ashok_protobufexample_employee_Employee_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_employee_Employee_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_ashok_protobufexample_employee_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ashok_protobufexample_employee_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_employee_EmployeeList_descriptor,
        new java.lang.String[] { "Employee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
