// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.protobuff;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ashok.protobufexample.employee.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 emp_id = 1;</code>
   */
  int getEmpId();

  /**
   * <code>int32 salary = 2;</code>
   */
  int getSalary();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string department = 5;</code>
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 5;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>string email = 6;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 age = 7;</code>
   */
  int getAge();

  /**
   * <code>repeated .ashok.protobufexample.employee.Employee.PhoneNumber phones = 8;</code>
   */
  java.util.List<com.example.protobuff.Employee.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee.PhoneNumber phones = 8;</code>
   */
  com.example.protobuff.Employee.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee.PhoneNumber phones = 8;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee.PhoneNumber phones = 8;</code>
   */
  java.util.List<? extends com.example.protobuff.Employee.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee.PhoneNumber phones = 8;</code>
   */
  com.example.protobuff.Employee.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
