// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.protobuff;

public interface EmployeeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ashok.protobufexample.employee.EmployeeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ashok.protobufexample.employee.Employee employee = 1;</code>
   */
  java.util.List<com.example.protobuff.Employee> 
      getEmployeeList();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee employee = 1;</code>
   */
  com.example.protobuff.Employee getEmployee(int index);
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee employee = 1;</code>
   */
  int getEmployeeCount();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee employee = 1;</code>
   */
  java.util.List<? extends com.example.protobuff.EmployeeOrBuilder> 
      getEmployeeOrBuilderList();
  /**
   * <code>repeated .ashok.protobufexample.employee.Employee employee = 1;</code>
   */
  com.example.protobuff.EmployeeOrBuilder getEmployeeOrBuilder(
      int index);
}
