// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.example.tutorial.protos.Students;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.StudentInfo student = 1;</code>
   */
  java.util.List<com.example.tutorial.protos.Students.StudentInfo> 
      getStudentList();
  /**
   * <code>repeated .tutorial.StudentInfo student = 1;</code>
   */
  com.example.tutorial.protos.Students.StudentInfo getStudent(int index);
  /**
   * <code>repeated .tutorial.StudentInfo student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .tutorial.StudentInfo student = 1;</code>
   */
  java.util.List<? extends com.example.tutorial.protos.Students.StudentInfoOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .tutorial.StudentInfo student = 1;</code>
   */
  com.example.tutorial.protos.Students.StudentInfoOrBuilder getStudentOrBuilder(
      int index);
}
