// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.example.tutorial.protos.Students;

public interface StudentInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.StudentInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_Name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_Name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_Name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>int32 roll_Number = 3;</code>
   */
  int getRollNumber();

  /**
   * <code>double cgpa = 4;</code>
   */
  double getCgpa();
}
