// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.protobufexamplejava;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_contracts_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_contracts_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_contracts_Date_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_contracts_Date_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ashok_protobufexample_contracts_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ashok_protobufexample_contracts_Money_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\037ashok.protobufexample." +
      "contracts\032\037google/protobuf/timestamp.pro" +
      "to\"\204\002\n\010Customer\022\n\n\002id\030\001 \001(\003\022\r\n\005photo\030\002 \001" +
      "(\014\022\014\n\004name\030\003 \001(\t\0228\n\tbirthdate\030\004 \001(\0132%.as" +
      "hok.protobufexample.contracts.Date\0227\n\007ba" +
      "lance\030\005 \001(\0132&.ashok.protobufexample.cont" +
      "racts.Money\022-\n\tcreatedAt\030\006 \001(\0132\032.google." +
      "protobuf.Timestamp\022-\n\tupdatedAt\030\007 \001(\0132\032." +
      "google.protobuf.Timestamp\"0\n\004Date\022\014\n\004yea" +
      "r\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\"<\n\005M" +
      "oney\022\025\n\rcurrency_code\030\001 \001(\t\022\r\n\005units\030\002 \001" +
      "(\003\022\r\n\005nanos\030\003 \001(\005B2\n\037com.example.protobu" +
      "fexamplejavaB\rCustomerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_ashok_protobufexample_contracts_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ashok_protobufexample_contracts_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_contracts_Customer_descriptor,
        new java.lang.String[] { "Id", "Photo", "Name", "Birthdate", "Balance", "CreatedAt", "UpdatedAt", });
    internal_static_ashok_protobufexample_contracts_Date_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ashok_protobufexample_contracts_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_contracts_Date_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
    internal_static_ashok_protobufexample_contracts_Money_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ashok_protobufexample_contracts_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ashok_protobufexample_contracts_Money_descriptor,
        new java.lang.String[] { "CurrencyCode", "Units", "Nanos", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
