// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.protobufexamplejava;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ashok.protobufexample.contracts.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>bytes photo = 2;</code>
   */
  com.google.protobuf.ByteString getPhoto();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.ashok.protobufexample.contracts.Date birthdate = 4;</code>
   */
  boolean hasBirthdate();
  /**
   * <code>.ashok.protobufexample.contracts.Date birthdate = 4;</code>
   */
  com.example.protobufexamplejava.Date getBirthdate();
  /**
   * <code>.ashok.protobufexample.contracts.Date birthdate = 4;</code>
   */
  com.example.protobufexamplejava.DateOrBuilder getBirthdateOrBuilder();

  /**
   * <code>.ashok.protobufexample.contracts.Money balance = 5;</code>
   */
  boolean hasBalance();
  /**
   * <code>.ashok.protobufexample.contracts.Money balance = 5;</code>
   */
  com.example.protobufexamplejava.Money getBalance();
  /**
   * <code>.ashok.protobufexample.contracts.Money balance = 5;</code>
   */
  com.example.protobufexamplejava.MoneyOrBuilder getBalanceOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
