// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.protobufexamplejava;

public interface DateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ashok.protobufexample.contracts.Date)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
   * a year.
   * </pre>
   *
   * <code>int32 year = 1;</code>
   */
  int getYear();

  /**
   * <pre>
   * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
   * month and day.
   * </pre>
   *
   * <code>int32 month = 2;</code>
   */
  int getMonth();

  /**
   * <pre>
   * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
   * to specify a year by itself or a year and month where the day isn't
   * significant.
   * </pre>
   *
   * <code>int32 day = 3;</code>
   */
  int getDay();
}
