// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.protobufexamplejava;

public interface MoneyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ashok.protobufexample.contracts.Money)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The three-letter currency code defined in ISO 4217.
   * </pre>
   *
   * <code>string currency_code = 1;</code>
   */
  java.lang.String getCurrencyCode();
  /**
   * <pre>
   * The three-letter currency code defined in ISO 4217.
   * </pre>
   *
   * <code>string currency_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>int64 units = 2;</code>
   */
  long getUnits();

  /**
   * <code>int32 nanos = 3;</code>
   */
  int getNanos();
}
