// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package Schema.SearchRequestPackage;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>int32 page_number = 2;</code>
   */
  int getPageNumber();

  /**
   * <code>int32 result_per_page = 3;</code>
   */
  int getResultPerPage();

  /**
   * <code>.SearchRequest.Corpus corpus = 4;</code>
   */
  int getCorpusValue();
  /**
   * <code>.SearchRequest.Corpus corpus = 4;</code>
   */
  Schema.SearchRequestPackage.SearchRequest.Corpus getCorpus();
}
